# Generated by Django 5.1.1 on 2024-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0004_alter_customuser_email_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
