# Generated by Django 5.1.1 on 2024-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0005_passwordresetrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='aanaa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='balina_lafa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='gosa_tajajila',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='haala_beenya',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='iddo_adda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='kan_qophesse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='madda_lafa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='magaalaa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='qamaa_qophaef',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_iddo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_qophaef',
            field=models.CharField(max_length=100),
        ),
    ]
