# Generated by Django 5.1.1 on 2024-10-06 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0006_alter_shegarlandform_aanaa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shegarlandform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='aanaa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='balina_lafa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='gosa_tajajila',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='haala_beenya',
            field=models.CharField(choices=[('Bilisaa', 'Bilisaa'), ('Beenyaa kan qabu', 'Beenyaa kan qabu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='iddo_adda',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='kan_qophesse',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='madda_lafa',
            field=models.CharField(choices=[('ISA Digame', 'ISA Digame'), ('Waligalten kan cite', 'Waligalten kan cite'), ('Lafa motumma', 'Lafa motumma'), ('Lafa walini', 'Lafa walini'), ('Lafa benyan itti kaffalame', 'Lafa benyan itti kaffalame'), ("Lafa seran ala qabame bankitti debi'e", "Lafa seran ala qabame bankitti debi'e"), ('kan biroo', 'kan biroo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='magaalaa',
            field=models.CharField(choices=[('SU', 'SU'), ('MA', 'MA'), ('LXLD', 'LXLD'), ('KJ', 'KJ'), ('KF', 'KF'), ('GLN', 'GLN'), ('FU', 'FU'), ('GGUD', 'GGUD'), ('SAB', 'SAB'), ('MN', 'MN'), ('GGUJ', 'GGUJ'), ('BU', 'BU')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='qamaa_qophaef',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_iddo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_qophaef',
            field=models.CharField(max_length=40),
        ),
    ]
