# Generated by Django 5.1.1 on 2024-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0008_alter_shegarlandform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shegarlandform',
            name='Mallattoo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='bal_lafa_bahi_tae',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='bal_lafa_hafe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='guyyaa_bahi_tae',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='kan_bahi_taasise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='qaama_bahi_tahef',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='tajajila_bahi_tahef',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='aanaa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='gosa_tajajila',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='iddo_adda',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='kan_qophesse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='qamaa_qophaef',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_qophaef',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
