# Generated by Django 5.1.1 on 2024-10-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0011_alter_shegarlandform_gosa_tajajila_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='qamaa_qophaef',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
